name: bsmi_base
description: BSMI team base library, include time parse and convert , string format and convert, and other more tools.
version: 1.0.5
homepage: https://kb.bsmi.info

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  yaml: ^3.1.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
